theme: minima
author: Bartu Yaman
title: Welcome!
description: Hello and welcome! My name is Bartu Yaman and I am a computational physicist with concentraions in condensed matter physics, plasma physics and quantum computing.

# Activate a "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"
